name: star_education_center
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0" # Update to a range that supports null safety and Dart 3.x

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.6.0
  uuid: ^4.4.2
  cloud_firestore: ^5.4.4
  intl: ^0.19.0
  test: ^1.25.2 # Ensure this is updated to a null-safe version

dev_dependencies:
  integration_test:
    sdk: flutter # Correcting this section to avoid issues
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # For good coding practices and lints

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/certificate/
    - assets/courses/

  # Uncomment if needed for fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
